"""Freeze the v2 tuned hyperparameters (docs/deviations.md, 2026-10-08).

    python scripts/tune/freeze_v2.py

Reads ``results/tuning/tuning_v2_<model>_a<anchor>.json`` for S and D-state (each must hold the configured number
of COMPLETE trials and the backbone options of ``v2.selected``), writes ``write_result("tuning_v2_summary")``
from a clean tree, then ``configs/tuned_v2.yaml``: the best parameters per (model, anchor), ``D`` as a copy of
D-state, and ``arch`` with the fixed backbone options that every v2 run adds to its architecture.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

sys.path.insert(0, str(Path(__file__).resolve().parent))
from freeze import PARAM_ORDER

TUNED_V2 = ROOT / "configs" / "tuned_v2.yaml"
MODELS = ("S", "D-state")


def main() -> None:
    from dftgnn.config import load_config
    from dftgnn.io.results import write_result
    from dftgnn.train import code_sha

    cfg = load_config()
    arch = cfg.v2.variants[cfg.v2.selected]
    studies = {}
    for m in MODELS:
        for a in cfg.tuning.anchors:
            pay = json.loads((ROOT / "results" / "tuning" / f"tuning_v2_{m}_a{a}.json").read_text())["payload"]
            if pay["n_complete"] != cfg.tuning.optuna_trials_per_model_per_anchor:
                raise SystemExit(f"v2_{m}_a{a}: {pay['n_complete']} complete trials")
            if pay.get("arch") != arch:
                raise SystemExit(f"v2_{m}_a{a}: arch {pay.get('arch')} != {arch}")
            studies[(m, a)] = pay
    summary = {"selected_variant": cfg.v2.selected, "arch": arch,
               "best": {f"{m}|{a}": {"best_value": p["best_value"], "best_trial": p["best_trial"],
                                     "best_params": p["best_params"], "top5_spread": p["top5_spread"],
                                     "trials_reaching_cap": len(p["trials_reaching_cap"])}
                        for (m, a), p in studies.items()},
               "tuned_file": "configs/tuned_v2.yaml"}
    print(write_result("tuning_v2_summary", summary, config=cfg))

    import yaml

    def flow(d: dict) -> str:            # exact float round-trip, as in freeze.py
        return yaml.safe_dump(d, default_flow_style=True, sort_keys=False, width=1000).strip()

    lines = ["# v2 tuned hyperparameters (docs/deviations.md, 2026-10-08). Generated by scripts/tune/freeze_v2.py from",
             "# results/tuning/tuning_v2_<model>_a<anchor>.json (30 COMPLETE trials per study, §6 protocol).",
             f"# Tuning code commit: {code_sha()}. Do not edit by hand.",
             "version: tuned-v2", "d_variant: D-state",
             f"arch: {flow(dict(arch))}", "models:"]
    for m in (*MODELS, "D"):
        src = "D-state" if m == "D" else m
        lines.append(f"  {m}:" + ("   # copy of D-state" if m == "D" else ""))
        for a in cfg.tuning.anchors:
            p = studies[(src, a)]["best_params"]
            lines.append(f"    {a}: {flow({k: p[k] for k in PARAM_ORDER})}")
    TUNED_V2.write_text("\n".join(lines) + "\n")
    back = yaml.safe_load(TUNED_V2.read_text())
    for (m, a), pay in studies.items():
        if back["models"][m][a] != pay["best_params"]:
            raise SystemExit(f"{m} a{a}: written values do not round-trip")
    if back["arch"] != arch:
        raise SystemExit("arch does not round-trip")
    print(TUNED_V2)


if __name__ == "__main__":
    main()
