"""S08 step 4: freeze the tuned hyperparameters and select D's injection variant.

    python scripts/tune/freeze.py

Reads the twelve study results ``results/tuning/tuning_<model>_a<anchor>.json`` (each must hold the
configured number of COMPLETE trials) and applies the logged rule (ANALYSIS_PLAN section 4; clarification
in docs/deviations.md, 2026-10-07): the D variant with the lower mean over the three anchors of its
studies' best-trial validation MAE becomes D. Then, in this order:

1. ``write_result("tuning_summary")`` (from a clean tree), with both means and the decision;
2. ``configs/tuned_v1.yaml``: best parameters per (model, anchor) for S, D-state, D-late and P1, and under
   ``D`` a copy of the selected variant;
3. ``models.injection_mode`` in ``configs/config.yaml``;
4. ``docs/tuning.md``.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

TUNED = ROOT / "configs" / "tuned_v1.yaml"
CONFIG = ROOT / "configs" / "config.yaml"
DOC = ROOT / "docs" / "tuning.md"
MODELS = ("S", "D-state", "D-late", "P1")
PARAM_ORDER = ("learning_rate", "weight_decay", "hidden_width", "megnet_blocks", "dropout", "batch_size",
               "readout_mlp_width", "pooling")


def load_studies(cfg) -> dict:
    out = {}
    for m in MODELS:
        for a in cfg.tuning.anchors:
            f = ROOT / "results" / "tuning" / f"tuning_{m}_a{a}.json"
            pay = json.loads(f.read_text())["payload"]
            if pay["n_complete"] != cfg.tuning.optuna_trials_per_model_per_anchor:
                raise SystemExit(f"{f.name}: {pay['n_complete']} complete trials")
            out[(m, a)] = pay
    return out


def select_d(studies: dict, anchors) -> dict:
    means = {v: sum(studies[(v, a)]["best_value"] for a in anchors) / len(anchors) for v in ("D-state", "D-late")}
    chosen = min(means, key=lambda v: (means[v], v))
    return {"rule": "lower mean over the anchors of the best-trial validation MAE (E_f, eV)",
            "means_eV": means, "per_anchor_eV": {v: {str(a): studies[(v, a)]["best_value"] for a in anchors}
                                                 for v in means},
            "selected": chosen, "difference_eV": means["D-state"] - means["D-late"],
            "tie": means["D-state"] == means["D-late"]}


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:.3g}" if (abs(v) < 1e-2 or abs(v) >= 1e3) else f"{v:.4f}".rstrip("0").rstrip(".")
    return str(v)


def tuned_yaml(studies: dict, decision: dict, anchors, commit: str) -> str:
    """The frozen file. Values go through ``yaml.safe_dump`` so that floats round-trip exactly (PyYAML reads
    ``1e-05`` without a decimal point as a string)."""
    import yaml

    def flow(d: dict) -> str:
        return yaml.safe_dump(d, default_flow_style=True, sort_keys=False, width=1000).strip()

    header = [
        "# Tuned hyperparameters, frozen in S08 (tag tuned-v1). Generated by scripts/tune/freeze.py from",
        "# results/tuning/tuning_<model>_a<anchor>.json (30 COMPLETE Optuna TPE trials per study; objective: best",
        "# validation MAE, E_f in eV for S and D, standardised descriptors for P1). Budgets map to anchors by",
        "# tuning.budget_to_anchor; the Kiyohara split uses anchor 654 (docs/deviations.md, 2026-10-07).",
        f"# Tuning code commit: {commit}. Do not edit by hand; scripts/check_prereg.py verifies this file.",
        "version: tuned-v1",
        f"d_variant: {decision['selected']}",
        "d_selection:",
        f"  rule: {decision['rule']}",
        f"  mean_best_val_mae_eV: {flow(decision['means_eV'])}",
        "models:",
    ]
    lines = list(header)
    for m in (*MODELS, "D"):
        src = decision["selected"] if m == "D" else m
        lines.append(f"  {m}:" + (f"   # copy of {src}, the selected variant" if m == "D" else ""))
        for a in anchors:
            p = studies[(src, a)]["best_params"]
            lines.append(f"    {a}: {flow({k: p[k] for k in PARAM_ORDER})}")
    return "\n".join(lines) + "\n"


def set_injection_mode(text: str, variant: str) -> str:
    new, n = re.subn(r"^(  injection_mode: )\S+.*$",
                     rf"\g<1>{variant}   # selected by models.D.injection_selection in S08 (docs/tuning.md)",
                     text, count=1, flags=re.MULTILINE)
    if n != 1:
        raise SystemExit("models.injection_mode not found in the config")
    return new


def doc(studies: dict, decision: dict, cfg, wave_info: dict | None) -> str:
    anchors = cfg.tuning.anchors
    L = ["# Hyperparameter tuning (S08)", "",
         ("Generated by `scripts/tune/freeze.py` from `results/tuning/` and `results/tuning_summary.json`. "
         "Protocol: ANALYSIS_PLAN section 6 with the clarifications of `docs/deviations.md` (2026-10-07): one "
         "Optuna study per model and anchor, `TPESampler(seed=0)`, no pruning, 30 COMPLETE trials, seed-0 trials "
         "on resample 0's nested training hosts, one validation set per anchor shared by all four models, "
         f"max_epochs {cfg.training.max_epochs} and patience {cfg.training.early_stopping.patience}. The test "
         "hosts of resample 0 were removed from memory in every tuning process."), "",
         ("The objective is the best validation MAE of a trial: E_f in eV for S, D-state and D-late; the mean "
         "absolute error over the 22 standardised descriptors (dimensionless) for P1."), "",
         "## Validation sets", "",
         "| Anchor B | Training hosts (fitted) | Validation hosts | Training sites | Validation sites |",
         "|---:|---:|---:|---:|---:|"]
    for a in anchors:
        v = studies[("S", a)]["validation"]
        L.append(f"| {a} | {v['n_train_hosts']} | {v['n_val_hosts']} | {v['n_train_sites']} | {v['n_val_sites']} |")
    v50 = studies[("S", 50)]["validation"]
    L += ["", (f"The 50-host anchor's objective rests on {v50['n_val_hosts']} validation hosts "
          f"({v50['n_val_sites']} sites). It is noisy: differences between trials at this anchor of the order of "
          "the top-5 spread below are not meaningful, and the a50 hyperparameters should be read as one "
          "reasonable setting rather than an optimum."), "",
          "## Best trial per study", "",
          ("| Model | Anchor | Best val. MAE | Top-5 spread | Best trial (epoch / run) | Non-finite | Failed | "
          "Reached cap | Boundary hits |"),
          "|---|---:|---:|---:|---|---:|---:|---:|---|"]
    for m in MODELS:
        for a in anchors:
            s = studies[(m, a)]
            bh = ", ".join(f"{k} ({v})" for k, v in s["boundary_hits"].items()) or "none"
            L.append(f"| {m} | {a} | {s['best_value']:.4f} | {s['top5_spread']:.4f} | "
                     f"{s['best_trial']} ({s['best_trial_best_epoch'] + 1} / {s['best_trial_epochs_run']}) | "
                     f"{s['n_nonfinite']} | {s['n_failed']} | {len(s['trials_reaching_cap'])} | {bh} |")
    L += ["", ("Best epoch is counted from 1. \"Reached cap\" counts the complete trials that ran all "
          f"{cfg.training.max_epochs} epochs without early stopping. Boundary hits (informational only): "
          f"{studies[('S', 50)]['boundary_rule']}. Top-5 spread is the fifth-best minus the best objective value, "
          "a measure of how flat the objective is near its minimum."), "",
          "## Best parameters", "",
          "| Model | Anchor | " + " | ".join(PARAM_ORDER) + " |", "|---|---:|" + "---|" * len(PARAM_ORDER)]
    for m in MODELS:
        for a in anchors:
            p = studies[(m, a)]["best_params"]
            L.append(f"| {m} | {a} | " + " | ".join(_fmt(p[k]) for k in PARAM_ORDER) + " |")
    me = decision["means_eV"]
    L += ["", "## Selection of D", "",
          f"Rule (logged before tuning): {decision['rule']}.", "",
          "| Variant | " + " | ".join(f"a{a}" for a in anchors) + " | Mean |", "|---|" + "---:|" * (len(anchors) + 1)]
    for v in ("D-state", "D-late"):
        L.append(f"| {v} | " + " | ".join(f"{decision['per_anchor_eV'][v][str(a)]:.4f}" for a in anchors)
                 + f" | {me[v]:.4f} |")
    other = "D-late" if decision["selected"] == "D-state" else "D-state"
    L += ["", (f"**D = {decision['selected']}** (mean {me[decision['selected']]:.4f} eV against {me[other]:.4f} eV for "
          f"{other}; difference {abs(decision['difference_eV']):.4f} eV). `models.injection_mode` is set to "
          f"`{decision['selected']}` and its tuned values are copied under `D` in `configs/tuned_v1.yaml`. "
          f"{other} is reported from its tuning runs only, in the SI (ANALYSIS_PLAN section 12d).")]
    if wave_info:
        L += ["", "## Cost", "", "| Wave | Anchor | Wall time (h) | GPU-hours |", "|---|---:|---:|---:|"]
        for w in wave_info["waves"]:
            L.append(f"| {w['wave']} | {w['anchor']} | {w['wall_h']:.2f} | {w['gpu_h']:.2f} |")
        L += ["", (f"Total {wave_info['total_gpu_h']:.2f} GPU-hours on one L40S with four studies sharing the card "
              f"under CUDA MPS, against {wave_info['central_gpu_h']:.1f} (central) and "
              f"{wave_info['upper_gpu_h']:.1f} (upper) projected in `docs/cost_table.md`.")]
    return "\n".join(L) + "\n"


def main() -> None:
    import argparse

    from dftgnn.config import load_config
    from dftgnn.io.results import write_result

    ap = argparse.ArgumentParser()
    ap.add_argument("--waves", help="JSON with the measured wave wall times (written into the summary)")
    a = ap.parse_args()
    cfg = load_config()
    studies = load_studies(cfg)
    anchors = cfg.tuning.anchors
    decision = select_d(studies, anchors)
    waves = json.loads(Path(a.waves).read_text()) if a.waves else None
    commits = {s["pod_commit"] for s in studies.values()}
    payload = {
        "decision": decision,
        "studies": {f"{m}_a{an}": {k: s[k] for k in ("best_value", "best_params", "best_trial", "top5_spread",
                                                      "boundary_hits", "n_complete", "n_failed", "n_nonfinite",
                                                      "trials_reaching_cap", "validation", "best_trial_best_epoch",
                                                      "best_trial_epochs_run", "objective")}
                    for (m, an), s in studies.items()},
        "validation_sets": {str(an): studies[("S", an)]["validation"] for an in anchors},
        "tuning_commits": sorted(commits), "waves": waves,
        "tuned_file": "configs/tuned_v1.yaml",
    }
    print(write_result("tuning_summary", payload, config=cfg))
    TUNED.write_text(tuned_yaml(studies, decision, anchors, ",".join(sorted(commits))))
    CONFIG.write_text(set_injection_mode(CONFIG.read_text(), decision["selected"]))
    DOC.write_text(doc(studies, decision, cfg, waves))
    print(json.dumps(decision, indent=1))


if __name__ == "__main__":
    main()
