name: dftgnn
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pymatgen
  - ase
  - matplotlib
  - seaborn
  - optuna
  - pyyaml
  - pydantic
  - jupyter
  - pytest
  - ruff
  - colorspacious
  - tqdm
  - pytorch
  - pip
  - pip:
      - torch_geometric
      - mace-torch
